### ISSUE TITLE
Towards version 3

### ISSUE THREAD

**Issue by jakob-keller** [grantjenks/python-sortedcontainers#199] opened 2022-08-19 20:07 UTC
Hello and thanks for this great library!

I recently migrated away from my own primitive sorted container implementation and have never looked back.

There is only one feature that is important to me, but is currently not provided: **type hints**. And it looks to me as if the community feels the same: #68, #155 

I am reasonably experienced with inline type hints and would offer to prepare a PR for that purpose, or pick up the work already done by others: #107, #136 

One precondition would be to drop support for [EOL Python versions](https://devguide.python.org/versions/), which is anything older than Python 3.7 at this point. I could draft a corresponding PR, if there is interest.

This might be the ground work for sortedcontainers version 3, to be followed be other issues already tagged as V3.

How does @grantjenks feel about this?

**Comment by grantjenks** [comment] 2022-08-20 15:17
The V3 tag is just old. I’ve deleted it.

**Comment by grantjenks** [comment] 2022-08-20 15:18
I use type hints at work and haven’t liked them much. As I said in #68, I’d prefer if someone added support to the type shed and maintained them there for a while.

**Comment by jakob-keller** [comment] 2022-08-20 15:19
> I use type hints at work and haven’t liked them much. As I said in #68, I’d prefer if someone added support to the type shed and maintained them there for a while.

I understand and will look into that. Thanks for clarifying!

**Comment by grantjenks** [comment] 2022-08-20 15:34
Regarding EOL Python versions, *might* want to keep Python 3.6 as it’s still the standard in Cent OS 7 which is not yet EOL.

**Comment by grantjenks** [comment] 2022-08-20 15:35
Otherwise, closing as a dupe of #68 regarding type hints.

**Closed by grantjenks** 2022-08-20 15:35 UTC

**Comment by jakob-keller** [comment] 2022-08-20 15:40
> Regarding EOL Python versions, _might_ want to keep Python 3.6 as it’s still the standard in Cent OS 7 which is not yet EOL.

Fair point. Of course, removing support for CPython 3.6 only affects future releases of sortedcontainers. Any existing releases continue to be available e.g. on PyPI and won't break dependencies for Cent OS 7 users or elsewhere.
