### ISSUE TITLE
Type hints support for mypy usage...

### ISSUE THREAD

**Issue by Felix-neko** [grantjenks/python-sortedcontainers#155] opened 2020-08-21 20:49 UTC
Hi folks! And thank you for you great project.

Don't you have any plans to support type hints for your library? We use `mypy`, and it can be very useful...

**Comment by Zac-HD** [comment] 2020-09-09 08:56
See #68, #107, #136.

**Comment by grantjenks** [comment] 2022-08-20 15:12
Dupe of #68

**Closed by grantjenks** 2022-08-20 15:12 UTC
