### ISSUE TITLE
What about dictionaries sorted by value?

### ISSUE THREAD

**Issue by matteodellamico** [grantjenks/python-sortedcontainers#146] opened 2020-05-11 17:52 UTC
Hi!

Unless I'm missing something, sortedcontainers doesn't support dictionaries sorted by value. This is useful to implement priority queues (à-la heapq) where an item's priority can change over time. For example, graph algorithms (e.g., Dijkstra's algorithm for shortest paths) benefit from this. Here's an old Python cookbook recipe of mine for something like that (based, in turn, on an idea by David Eppstein): http://code.activestate.com/recipes/522995-priority-dict-a-priority-queue-with-updatable-prio/ .

I wonder if sortedcontainers would be a good place to put a similar container in a widely used library.

**Comment by grantjenks** [comment] 2020-05-11 18:06
The data type is in the sortedcollections library and is based on sortedcontainers: http://www.grantjenks.com/docs/sortedcollections/valuesorteddict.html

**Comment by grantjenks** [comment] 2020-05-11 18:06
See also #110

**Comment by matteodellamico** [comment] 2020-05-11 18:10
Wow, I discover now sortedcollections. Thanks!

**Comment by grantjenks** [comment] 2020-05-11 18:11
Also dupe of #57

**Closed by grantjenks** 2020-05-11 18:11 UTC
